# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import mysql.connector as a

con = a.connect(host="localhost",user="root",passwd="",database="library1")
class delete_book(object):
    def dbook(self):
        book_code = self.lineEdit_3.text()
        a = 'delete from books where BCODE=%s'
        data = (book_code,)
        c = con.cursor()
        c.execute(a,data)
        con.commit()
        self.lineEdit_3.hide()
        self.delete_book.hide()
        self.label_4.setText('success !! ')
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/library-logo-design-template-45579f2f9eaf725821b915b523f191eb_screen.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -10, 821, 621))
        self.label.setMinimumSize(QtCore.QSize(821, 621))
        self.label.setMaximumSize(QtCore.QSize(821, 621))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/library2.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 240, 231, 51))
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-weight:bold;\n"
"font: 87 14pt \"Segoe UI Black\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(440, 250, 121, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 30, 461, 51))
        self.label_6.setStyleSheet("color: rgb(91, 255, 62);\n"
"font-weight:bold;\n"
"font: 87 22pt \"Segoe UI Black\";\n"
"border-style:solid;\n"
"border-width:5px;\n"
"border-color:rgb(197, 49, 255);\n"
"background-color: rgb(255, 35, 39);")
        self.label_6.setObjectName("label_6")
        self.delete_book = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.dbook())
        self.delete_book.setGeometry(QtCore.QRect(340, 420, 91, 51))
        self.delete_book.setStyleSheet("background-color: rgb(212, 255, 0);\n"
"color:rgb(0, 0, 0);\n"
"font-weight:bold;\n"
"font-size:15px;")
        self.delete_book.setObjectName("delete_book")

       
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LIBRARY MANAGEMENT"))
        self.label_4.setText(_translate("MainWindow", "BOOK CODE          :"))
        self.label_6.setText(_translate("MainWindow", "                BOOK DELETION"))
        self.delete_book.setText(_translate("MainWindow", "DELETE"))
       


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = delete_book()
    ui.setupUi(MainWindow)

    MainWindow.show()
    sys.exit(app.exec_())
