# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WELCOME.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from book_issue import book_issue
from book_submit import book_submit
from add_book import add_book
from delete_book import delete_book
class welcome(object):
    def issue_book(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = book_issue()
      
        self.ui.setupUi(self.window)
        self.window.show()


    def submit_book(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = book_submit()
        self.ui.setupUi(self.window)
        self.window.show()

    def book_add(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = add_book()
        self.ui.setupUi(self.window)
        self.window.show()
    def book_delete(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = delete_book()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 600)
        MainWindow.setMinimumSize(QtCore.QSize(797, 600))
        MainWindow.setMaximumSize(QtCore.QSize(797, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/library-logo-design-template-45579f2f9eaf725821b915b523f191eb_screen.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 811, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/library2.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 160, 131, 61))
        self.pushButton.setStyleSheet("background-color:rgb(191, 0, 255);\n"
"color:rgb(0, 255, 0);\n"
"font: 12pt \"Segoe Print\";\n"
"font-weight:bold;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.issue_book())
        self.pushButton_2.setGeometry(QtCore.QRect(430, 160, 131, 61))
        self.pushButton_2.setStyleSheet("background-color:rgb(191, 0, 255);\n"
"color:rgb(0, 255, 0);\n"
"font: 12pt \"Segoe Print\";\n"
"font-weight:bold;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.submit_book())
        self.pushButton_3.setGeometry(QtCore.QRect(440, 260, 131, 61))
        self.pushButton_3.setStyleSheet("background-color:rgb(191, 0, 255);\n"
"color:rgb(0, 255, 0);\n"
"font: 12pt \"Segoe Print\";\n"
"font-weight:bold;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.book_delete())
        self.pushButton_4.setGeometry(QtCore.QRect(180, 260, 131, 61))
        self.pushButton_4.setStyleSheet("background-color:rgb(191, 0, 255);\n"
"color:rgb(0, 255, 0);\n"
"font: 12pt \"Segoe Print\";\n"
"font-weight:bold;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.book_add())
        self.pushButton_5.setGeometry(QtCore.QRect(320, 370, 131, 61))
        self.pushButton_5.setStyleSheet("background-color:rgb(191, 0, 255);\n"
"color:rgb(0, 255, 0);\n"
"font: 12pt \"Segoe Print\";\n"
"font-weight:bold;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 831, 111))
        self.label_2.setStyleSheet("background-color:rgb(97, 200, 255);\n"
"color:rgb(255, 20, 3);\n"
"font-size:28px;\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"font-weight:bold;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 10, 101, 91))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/Logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LIBRARY MANAGEMENT"))
        self.pushButton.setText(_translate("MainWindow", "VIEW BOOKS"))
        self.pushButton_2.setText(_translate("MainWindow", "ISSUE BOOK"))
        self.pushButton_3.setText(_translate("MainWindow", "SUBMIT BOOK"))
        self.pushButton_4.setText(_translate("MainWindow", "DELETE BOOK"))
        self.pushButton_5.setText(_translate("MainWindow", "ADD BOOK"))
        self.label_2.setText(_translate("MainWindow", "                                                         K.M.P.S  LIBRARY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = welcome()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
